// examples/8-react/comment-app/src1/CommentInput.js
/*
 * @Author: naluduo233
 * @Date: 2021-04-05 11:41:01
 * @LastEditors: naluduo233
 * @LastEditTime: 2021-04-05 12:19:49
 * @FilePath: /comment-app/src/CommentInput.js
 * @Description:
 */
import React, { Component } from "react";
class CommentInput extends Component {
  constructor() {
    super();
    this.state = {
      username: "",
      content: "",
    };
  }

  handleUsernameChange(event) {
    this.setState({
      username: event.target.value,
    });
  }

  handleContentChange(event) {
    this.setState({
      content: event.target.value,
    });
  }

  handleSubmit() {
    if (this.props.onSubmit) {
      const { username, content } = this.state;
      this.props.onSubmit({ username, content });
    }
    this.setState({ content: "" });
  }

  render() {
    return (
      <div className="comment-input">
        <div className="comment-field">
          <span className="comment-field-name">用户名：</span>
          <div className="comment-field-input">
            <input
              value={this.state.username}
              onChange={this.handleUsernameChange.bind(this)}
            />
          </div>
        </div>
        <div className="comment-field">
          <span className="comment-field-name">评论内容：</span>
          <div className="comment-field-input">
            <textarea
              value={this.state.content}
              onChange={this.handleContentChange.bind(this)}
            />
          </div>
        </div>
        <div className="comment-field-button">
          <button onClick={this.handleSubmit.bind(this)}>发布</button>
        </div>
      </div>
    );
  }
}
export default CommentInput;

// examples/7-vue/comment-app/src/components/comment-input.vue
<script>
export default {
  name: "CommentInput",
  props: {
    username: {
      type: String,
      default: "",
    },
  },
  data({ username }) {
    return {
      state: {
        username: username,
        content: "",
        textareaRef: null,
      },
    };
  },
  mounted() {
    // this.$refs.textareaRef.focus();
    document.querySelector("textarea").focus();
  },
  methods: {
    handleUsernameChange(event) {
      this.state.username = event.target.value;
    },
    handleContentChange(event) {
      this.state.content = event.target.value;
    },
    handleUsernameBlur(event) {
      // jsx 中必须这样传递带有 on 前缀，外部才能监听到
      this.$emit("onUserNameInputBlur", event.target.value);
    },
    handleSubmit() {
      const { username, content } = this.state;
      this.$emit("onSubmit", { username, content, createdTime: +new Date() });
      this.state.content = "";
    },
  },
  render() {
    return (
      <div className="comment-input">
        <div className="comment-field">
          <span className="comment-field-name">用户名：</span>
          <div className="comment-field-input">
            <input
              value={this.state.username}
              onBlur={this.handleUsernameBlur.bind(this)}
              onChange={this.handleUsernameChange.bind(this)}
            />
          </div>
        </div>
        <div className="comment-field">
          <span className="comment-field-name">评论内容：</span>
          <div className="comment-field-input">
            <textarea
              value={this.state.content}
              onChange={this.handleContentChange.bind(this)}
            />
          </div>
        </div>
        <div className="comment-field-button">
          <button onClick={this.handleSubmit.bind(this)}>发布</button>
        </div>
      </div>
    );
  },
};
</script>
